#!/usr/bin/env bash
set -e

helpstr="\
NAME
    jauthcli - run the JAuth command line interface

SYNOPSIS
    jauthcli [--new-window] [SECRET_FILE]

DESCRIPTION
    SECRET_FILE should be a text file where the first line is the secret key.  
    The default is ~/.s.

    This needs the JAuthCLI package in order to run.  By default, that 
    directory is a sibling of this script, and the parent directory is 
    automatically added to CLASSPATH.  If you have split this shell script and 
    the java code to two different places, you must set CLASSPATH appropriately 
    before running this script.

OPTIONS
    -h, --help
        Print this help.
    
    --new-window
        Launch it in a new xterm.

    --add-timestamp
        Add a column in the output noting the time at which each code became 
        valid.

REQUIREMENTS
    Java, probably >= 1.6.

    JAuthCLI is self-contained code, derived from a previous incarnation of 
    JAuth.  It does not require the current JAuth code.

AUTHOR
    John Brunelle
    Harvard FAS Research Computing

    JAuth from https://github.com/fasrc/JAuth
"

new_window=false
add_timestamp=false

args=$(getopt -l new-window,add-timestamp,help -o h -- "$@")
if [ $? -ne 0 ]; then
	exit 65  #(getopt will have written the error message)
fi
eval set -- "$args"
while [ ! -z "$1" ]; do
	case "$1" in
		--new-window)
			new_window=true
			;;
		--add-timestamp)
			add_timestamp=true
			;;

		-h | --help)
			echo -n "$helpstr"
			exit 0
			;;
		--) 
			shift
			break
			;;
	esac
	shift
done

secret_file="$1"
test -z "$secret_file" && secret_file=~/.s
if ! [ -r "$secret_file" ]; then
	echo "*** ERROR *** secret key file [$secret_file] does not exist or is not readable" >&2
	exit 1
fi

parentd="$(dirname "$0")"
test -d "$parentd"/JAuthCLI && export CLASSPATH="$parentd:$CLASSPATH"

set -u


#---

if $add_timestamp; then
	len=65
	javaarg='addtimestamp'
else
	len=39
	javaarg=''
fi

prefix=''
$new_window && prefix="xterm -geometry ${len}x5+16+14 -title jauthcli -e"

$prefix java JAuthCLI.Main "$secret_file" $javaarg  #(the argument to the java binary is a hack, and addition string argument will trigger it)
